### ISSUE TITLE
On board Nivi

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/on-boarding#2]
- [x] Schedule 2 1 hour meetings their first or first and second week
 - [x] Make sure they have git installed
 - [x] Complete Git intro 1
- [x] Complete sections 1 & 2 of https://learngitbranching.js.org/
- [x] Make sure they have GitHub setup and the correct access
- [x] Complete Git intro 2

**Comment by gj210** [comment]
This looks very handy. An ideal way to capture the thoroughness of any particular training.
