### ISSUE TITLE
Practice making an issue

### ISSUE THREAD

**Issue by meganrm** [allen-cell-animated/on-boarding#3]
## Problem
we need practice making an issue

## How to address it
We are going to practice opening and closing issues

this is similar to #2 
**Example**:
variable name: `myVariable`
_italics_
Here is my list of items to complete:

- [ ] item 1
- [ ] item 2
- [x] item 3
- [ ] item 4

https://allen-cell-animated.github.io/simularium-viewer/
[link to example](https://allen-cell-animated.github.io/simularium-viewer/)

**Comment by lynwilhelm** [comment]
Thanks again for the run through today!
